language: haskell
before_install: cabal install happy && PATH=/home/travis/.ghc-multi/7.6.3/bin:$PATH cabal install network
script: wget https://raw.github.com/ndmitchell/neil/master/travis.sh -O - --no-check-certificate --quiet | sh
